/**
 * InlineData - All data embedded directly in JavaScript
 * This eliminates the need for fetch() and allows the page to work as a static site
 */
const InlineData = {
    categories: [
        { "id": 1, "name": "Drones RTF" },
        { "id": 2, "name": "RC Aviones" },
        { "id": 3, "name": "RC Helicópteros" },
        { "id": 4, "name": "Componentes generales" },
        { "id": 5, "name": "Motores brushless" },
        { "id": 6, "name": "Hélices" },
        { "id": 7, "name": "Baterías LiPo" },
        { "id": 8, "name": "Electrónica FPV" },
        { "id": 9, "name": "Herramientas y soldadura" }
    ],

    brands: [
        { "id": 1, "name": "China Fly" },
        { "id": 2, "name": "Aero Parts" },
        { "id": 3, "name": "SkyRacer Tech" },
        { "id": 4, "name": "VoltAir RC" },
        { "id": 5, "name": "FPV Pro Line" }
    ],

    tags: [
        { "id": 1, "name": "Motor 2207" },
        { "id": 2, "name": "2450KV" },
        { "id": 3, "name": "6S" },
        { "id": 4, "name": "Freestyle" },
        { "id": 5, "name": "Racing" },
        { "id": 6, "name": "Long Range" },
        { "id": 7, "name": "Principiante" },
        { "id": 8, "name": "Intermedio" },
        { "id": 9, "name": "Avanzado" },
        { "id": 10, "name": "Frame 5 pulgadas" },
        { "id": 11, "name": "Frame 7 pulgadas" },
        { "id": 12, "name": "Batería LiPo" },
        { "id": 13, "name": "Cargador inteligente" },
        { "id": 14, "name": "Gafas FPV" },
        { "id": 15, "name": "VTx" },
        { "id": 16, "name": "Controladora de vuelo" },
        { "id": 17, "name": "ESC 4 en 1" },
        { "id": 18, "name": "Hélices 5x4.3" },
        { "id": 19, "name": "Kit de herramientas" },
        { "id": 20, "name": "Soldador" }
    ],

    specifications: [
        { "id": 1, "name": "Tamaño" },
        { "id": 2, "name": "Peso" },
        { "id": 3, "name": "Voltaje" },
        { "id": 4, "name": "Dimensiones" },
        { "id": 5, "name": "Materiales" },
        { "id": 6, "name": "KV del motor" },
        { "id": 7, "name": "Número de celdas (S)" },
        { "id": 8, "name": "Capacidad (mAh)" },
        { "id": 9, "name": "Conector" },
        { "id": 10, "name": "Uso recomendado" }
    ],

    products: [
        { "id": 1, "name": "Motor brushless 2207 2450KV AeroX Falcon", "description": "Motor brushless 2207 de alto rendimiento para drones freestyle 5 pulgadas.", "image": "url:/images/productos/motor-2207-falcon.jpg", "score": 4.9, "category_id": 5, "brand_id": 3, "price": 149900, "stock": 20 },
        { "id": 2, "name": "Motor brushless 2306 1750KV Raptor Pro V2", "description": "Motor 2306 1750KV ideal para drones de largo alcance en 6S.", "image": "url:/images/productos/motor-2306-raptor.jpg", "score": 4.7, "category_id": 5, "brand_id": 4, "price": 139900, "stock": 15 },
        { "id": 3, "name": "Frame freestyle 5 pulgadas Carbono X5", "description": "Frame de 5 pulgadas en fibra de carbono 3K para drones freestyle.", "image": "url:/images/productos/frame-x5.jpg", "score": 4.8, "category_id": 4, "brand_id": 2, "price": 189900, "stock": 12 },
        { "id": 4, "name": "Frame long range 7 pulgadas Explorer LR7", "description": "Frame de 7 pulgadas para vuelos de largo alcance, diseño ligero y resistente.", "image": "url:/images/productos/frame-lr7.jpg", "score": 4.6, "category_id": 4, "brand_id": 5, "price": 219900, "stock": 8 },
        { "id": 5, "name": "Hélices 5x4.3x3 triblades pack x4", "description": "Juego de 4 hélices triblade 5x4.3 para drones racing o freestyle.", "image": "url:/images/productos/helices-5x4-3.jpg", "score": 4.5, "category_id": 6, "brand_id": 1, "price": 19900, "stock": 60 },
        { "id": 6, "name": "Hélices 7x3.5x2 para long range pack x4", "description": "Hélices 7 pulgadas de dos palas optimizadas para eficiencia en largo alcance.", "image": "url:/images/productos/helices-7x3-5.jpg", "score": 4.4, "category_id": 6, "brand_id": 1, "price": 24900, "stock": 40 },
        { "id": 7, "name": "Batería LiPo 6S 1300mAh 100C FPV Pro", "description": "Batería LiPo de alto rendimiento para drones racing en 6S.", "image": "url:/images/productos/lipo-6s-1300.jpg", "score": 4.8, "category_id": 7, "brand_id": 5, "price": 129900, "stock": 25 },
        { "id": 8, "name": "Batería LiPo 4S 1500mAh 75C Freestyle", "description": "Batería 4S ideal para drones freestyle de 5 pulgadas.", "image": "url:/images/productos/lipo-4s-1500.jpg", "score": 4.6, "category_id": 7, "brand_id": 5, "price": 109900, "stock": 30 },
        { "id": 9, "name": "Controladora de vuelo F7 con OSD", "description": "FC F7 con OSD integrado, soporte para Betaflight e INAV.", "image": "url:/images/productos/fc-f7-osd.jpg", "score": 4.9, "category_id": 8, "brand_id": 4, "price": 209900, "stock": 18 },
        { "id": 10, "name": "ESC 4 en 1 45A BLHeli_32", "description": "Variador 4 en 1 de 45A con soporte 3–6S y firmware BLHeli_32.", "image": "url:/images/productos/esc-4en1-45a.jpg", "score": 4.7, "category_id": 8, "brand_id": 3, "price": 229900, "stock": 16 },
        { "id": 11, "name": "VTx 800mW 5.8GHz con SmartAudio", "description": "Transmisor de video 5.8GHz con potencia ajustable hasta 800mW.", "image": "url:/images/productos/vtx-800mw.jpg", "score": 4.6, "category_id": 8, "brand_id": 2, "price": 159900, "stock": 20 },
        { "id": 12, "name": "Antena FPV pagoda RHCP 5.8GHz", "description": "Antena tipo pagoda RHCP para gafas o dron FPV.", "image": "url:/images/productos/antena-pagoda.jpg", "score": 4.5, "category_id": 8, "brand_id": 1, "price": 49900, "stock": 50 },
        { "id": 13, "name": "Gafas FPV digitales 1080p", "description": "Gafas FPV con pantalla de alta resolución y receptor digital.", "image": "url:/images/productos/gafas-fpv-digitales.jpg", "score": 4.9, "category_id": 1, "brand_id": 4, "price": 1899900, "stock": 6 },
        { "id": 14, "name": "Kit de dron freestyle 5 pulgadas RTF", "description": "Kit completo listo para volar con control remoto, dron y receptor.", "image": "url:/images/productos/kit-freestyle-rtf.jpg", "score": 4.7, "category_id": 1, "brand_id": 3, "price": 2399900, "stock": 5 },
        { "id": 15, "name": "Transmisor de radio 2.4GHz multiprotocolo", "description": "Radio de control 2.4GHz con protocolo multiprotocolo y pantalla LCD.", "image": "url:/images/productos/radio-2-4ghz.jpg", "score": 4.8, "category_id": 4, "brand_id": 2, "price": 899900, "stock": 10 },
        { "id": 16, "name": "Kit de herramientas para drones", "description": "Kit con destornilladores, llaves hexagonales y accesorios para montaje.", "image": "url:/images/productos/kit-herramientas.jpg", "score": 4.4, "category_id": 9, "brand_id": 1, "price": 99900, "stock": 35 },
        { "id": 17, "name": "Soldador eléctrico 60W punta fina", "description": "Soldador de 60W con temperatura ajustable para electrónica.", "image": "url:/images/productos/soldador-60w.jpg", "score": 4.5, "category_id": 9, "brand_id": 2, "price": 79900, "stock": 28 },
        { "id": 18, "name": "Cargador balanceador dual 2x100W", "description": "Cargador inteligente con dos canales independientes hasta 6S.", "image": "url:/images/productos/cargador-2x100w.jpg", "score": 4.7, "category_id": 7, "brand_id": 4, "price": 369900, "stock": 9 },
        { "id": 19, "name": "Cableado de silicona 14AWG rojo/negro 1m", "description": "Par de cables de silicona 14AWG de alta flexibilidad.", "image": "url:/images/productos/cables-14awg.jpg", "score": 4.3, "category_id": 4, "brand_id": 5, "price": 15900, "stock": 80 },
        { "id": 20, "name": "Tornillería M3 acero inoxidable surtida", "description": "Set de tornillos M3 surtidos para montaje de drones y frames.", "image": "url:/images/productos/tornilleria-m3.jpg", "score": 4.6, "category_id": 4, "brand_id": 3, "price": 29900, "stock": 70 }
    ],

    productImages: [
        { "product_id": 1, "image": "url:/images/productos/motor-2207-falcon.jpg", "order": 1 },
        { "product_id": 1, "image": "url:/images/productos/motor-2207-falcon-2.jpg", "order": 2 },
        { "product_id": 2, "image": "url:/images/productos/motor-2306-raptor.jpg", "order": 1 },
        { "product_id": 2, "image": "url:/images/productos/motor-2306-raptor-2.jpg", "order": 2 },
        { "product_id": 3, "image": "url:/images/productos/frame-x5.jpg", "order": 1 },
        { "product_id": 3, "image": "url:/images/productos/frame-x5-2.jpg", "order": 2 },
        { "product_id": 4, "image": "url:/images/productos/frame-lr7.jpg", "order": 1 },
        { "product_id": 4, "image": "url:/images/productos/frame-lr7-2.jpg", "order": 2 },
        { "product_id": 5, "image": "url:/images/productos/helices-5x4-3.jpg", "order": 1 },
        { "product_id": 5, "image": "url:/images/productos/helices-5x4-3-2.jpg", "order": 2 },
        { "product_id": 6, "image": "url:/images/productos/helices-7x3-5.jpg", "order": 1 },
        { "product_id": 6, "image": "url:/images/productos/helices-7x3-5-2.jpg", "order": 2 },
        { "product_id": 7, "image": "url:/images/productos/lipo-6s-1300.jpg", "order": 1 },
        { "product_id": 7, "image": "url:/images/productos/lipo-6s-1300-2.jpg", "order": 2 },
        { "product_id": 8, "image": "url:/images/productos/lipo-4s-1500.jpg", "order": 1 },
        { "product_id": 8, "image": "url:/images/productos/lipo-4s-1500-2.jpg", "order": 2 },
        { "product_id": 9, "image": "url:/images/productos/fc-f7-osd.jpg", "order": 1 },
        { "product_id": 9, "image": "url:/images/productos/fc-f7-osd-2.jpg", "order": 2 },
        { "product_id": 10, "image": "url:/images/productos/esc-4en1-45a.jpg", "order": 1 },
        { "product_id": 10, "image": "url:/images/productos/esc-4en1-45a-2.jpg", "order": 2 },
        { "product_id": 11, "image": "url:/images/productos/vtx-800mw.jpg", "order": 1 },
        { "product_id": 11, "image": "url:/images/productos/vtx-800mw-2.jpg", "order": 2 },
        { "product_id": 12, "image": "url:/images/productos/antena-pagoda.jpg", "order": 1 },
        { "product_id": 12, "image": "url:/images/productos/antena-pagoda-2.jpg", "order": 2 },
        { "product_id": 13, "image": "url:/images/productos/gafas-fpv-digitales.jpg", "order": 1 },
        { "product_id": 13, "image": "url:/images/productos/gafas-fpv-digitales-2.jpg", "order": 2 },
        { "product_id": 14, "image": "url:/images/productos/kit-freestyle-rtf.jpg", "order": 1 },
        { "product_id": 14, "image": "url:/images/productos/kit-freestyle-rtf-2.jpg", "order": 2 },
        { "product_id": 15, "image": "url:/images/productos/radio-2-4ghz.jpg", "order": 1 },
        { "product_id": 15, "image": "url:/images/productos/radio-2-4ghz-2.jpg", "order": 2 },
        { "product_id": 16, "image": "url:/images/productos/kit-herramientas.jpg", "order": 1 },
        { "product_id": 16, "image": "url:/images/productos/kit-herramientas-2.jpg", "order": 2 },
        { "product_id": 17, "image": "url:/images/productos/soldador-60w.jpg", "order": 1 },
        { "product_id": 17, "image": "url:/images/productos/soldador-60w-2.jpg", "order": 2 },
        { "product_id": 18, "image": "url:/images/productos/cargador-2x100w.jpg", "order": 1 },
        { "product_id": 18, "image": "url:/images/productos/cargador-2x100w-2.jpg", "order": 2 },
        { "product_id": 19, "image": "url:/images/productos/cables-14awg.jpg", "order": 1 },
        { "product_id": 19, "image": "url:/images/productos/cables-14awg-2.jpg", "order": 2 },
        { "product_id": 20, "image": "url:/images/productos/tornilleria-m3.jpg", "order": 1 },
        { "product_id": 20, "image": "url:/images/productos/tornilleria-m3-2.jpg", "order": 2 }
    ],

    productSpecifications: [
        { "product_id": 1, "specification_id": 2, "value": "32 g" },
        { "product_id": 1, "specification_id": 4, "value": "N/A" },
        { "product_id": 1, "specification_id": 6, "value": "2450KV" },
        { "product_id": 1, "specification_id": 7, "value": "6S" },
        { "product_id": 1, "specification_id": 10, "value": "Racing" },
        { "product_id": 2, "specification_id": 2, "value": "32 g" },
        { "product_id": 2, "specification_id": 4, "value": "N/A" },
        { "product_id": 2, "specification_id": 6, "value": "1750KV" },
        { "product_id": 2, "specification_id": 7, "value": "6S" },
        { "product_id": 2, "specification_id": 10, "value": "Racing" },
        { "product_id": 3, "specification_id": 2, "value": "10 g" },
        { "product_id": 3, "specification_id": 4, "value": "5 pulgadas" },
        { "product_id": 3, "specification_id": 5, "value": "Fibra de carbono 3K" },
        { "product_id": 3, "specification_id": 10, "value": "Freestyle" },
        { "product_id": 7, "specification_id": 7, "value": "6S" },
        { "product_id": 7, "specification_id": 8, "value": "1300mAh" },
        { "product_id": 7, "specification_id": 3, "value": "22.2V" },
        { "product_id": 7, "specification_id": 9, "value": "XT60" },
        { "product_id": 7, "specification_id": 10, "value": "Racing / Freestyle" },
        { "product_id": 9, "specification_id": 2, "value": "10 g" },
        { "product_id": 9, "specification_id": 4, "value": "35x35 mm" },
        { "product_id": 9, "specification_id": 3, "value": "3-6S LiPo" },
        { "product_id": 9, "specification_id": 10, "value": "Control de vuelo" }
    ],

    productTagAssos: [
        { "tag_id": 1, "product_id": 1 },
        { "tag_id": 2, "product_id": 1 },
        { "tag_id": 3, "product_id": 1 },
        { "tag_id": 4, "product_id": 1 },
        { "tag_id": 9, "product_id": 1 },
        { "tag_id": 5, "product_id": 2 },
        { "tag_id": 3, "product_id": 2 },
        { "tag_id": 8, "product_id": 2 },
        { "tag_id": 4, "product_id": 3 },
        { "tag_id": 10, "product_id": 3 },
        { "tag_id": 9, "product_id": 3 },
        { "tag_id": 6, "product_id": 4 },
        { "tag_id": 11, "product_id": 4 },
        { "tag_id": 8, "product_id": 4 },
        { "tag_id": 7, "product_id": 5 },
        { "tag_id": 18, "product_id": 5 },
        { "tag_id": 8, "product_id": 5 },
        { "tag_id": 6, "product_id": 6 },
        { "tag_id": 8, "product_id": 6 },
        { "tag_id": 12, "product_id": 7 },
        { "tag_id": 9, "product_id": 7 },
        { "tag_id": 12, "product_id": 8 },
        { "tag_id": 8, "product_id": 8 },
        { "tag_id": 16, "product_id": 9 },
        { "tag_id": 9, "product_id": 9 },
        { "tag_id": 17, "product_id": 10 },
        { "tag_id": 8, "product_id": 10 },
        { "tag_id": 15, "product_id": 11 },
        { "tag_id": 8, "product_id": 11 },
        { "tag_id": 7, "product_id": 12 },
        { "tag_id": 9, "product_id": 13 },
        { "tag_id": 14, "product_id": 13 },
        { "tag_id": 4, "product_id": 14 },
        { "tag_id": 7, "product_id": 14 },
        { "tag_id": 8, "product_id": 14 },
        { "tag_id": 8, "product_id": 15 },
        { "tag_id": 19, "product_id": 16 },
        { "tag_id": 7, "product_id": 16 },
        { "tag_id": 20, "product_id": 17 },
        { "tag_id": 8, "product_id": 17 },
        { "tag_id": 13, "product_id": 18 },
        { "tag_id": 8, "product_id": 18 },
        { "tag_id": 7, "product_id": 19 },
        { "tag_id": 7, "product_id": 20 }
    ],

    coupons: [
        { "id": 1, "name": "Cupón basico", "disc_porcent": 10, "code": "basic1" }
    ]
};

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
    module.exports = InlineData;
}
